package com.vtth.food.entity;
// Generated May 20, 2016 3:45:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblFooddetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_fooddetail", catalog = "fooddb")
public class TblFooddetail implements java.io.Serializable {

    private int foodId;
    private TblFood tblFood;
    private String materialDetail;
    private String tutorial;
    private String source;

    public TblFooddetail() {
    }

    public TblFooddetail(TblFood tblFood) {
        this.tblFood = tblFood;
    }
    public TblFooddetail(TblFood tblFood, String materialDetail, String tutorial, String source) {
        this.tblFood = tblFood;
        this.materialDetail = materialDetail;
        this.tutorial = tutorial;
        this.source = source;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tblFood"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "FoodID", unique = true, nullable = false)
    public int getFoodId() {
        return this.foodId;
    }

    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public TblFood getTblFood() {
        return this.tblFood;
    }

    public void setTblFood(TblFood tblFood) {
        this.tblFood = tblFood;
    }

    @Column(name = "MaterialDetail", length = 6000)
    public String getMaterialDetail() {
        return this.materialDetail;
    }

    public void setMaterialDetail(String materialDetail) {
        this.materialDetail = materialDetail;
    }

    @Column(name = "Tutorial", length = 15000)
    public String getTutorial() {
        return this.tutorial;
    }

    public void setTutorial(String tutorial) {
        this.tutorial = tutorial;
    }

    @Column(name = "Source")
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
