package com.vtth.food.entity;
// Generated May 20, 2016 3:45:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user", catalog = "fooddb")
public class TblUser implements java.io.Serializable {

    private Integer userId;
    private String userName;
    private String password;
    private TblUserdetail tblUserdetail;

    public TblUser() {
    }

    public TblUser(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    public TblUser(String userName, String password, TblUserdetail tblUserdetail) {
        this.userName = userName;
        this.password = password;
        this.tblUserdetail = tblUserdetail;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "UserID", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "UserName", nullable = false)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "Password", nullable = false)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "tblUser")
    public TblUserdetail getTblUserdetail() {
        return this.tblUserdetail;
    }

    public void setTblUserdetail(TblUserdetail tblUserdetail) {
        this.tblUserdetail = tblUserdetail;
    }

}
