package com.vtth.foodapi.entity;
// Generated Jun 3, 2016 12:27:17 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCategory generated by hbm2java
 */
@Entity
@Table(name = "tbl_category", catalog = "fooddb")
public class TblCategory implements java.io.Serializable {

    /** . */
    private static final long serialVersionUID = 3740642910675476900L;

    private int categoryId;
    private String categoryName;

    public TblCategory() {
    }

    public TblCategory(String categoryName) {
        this.categoryName = categoryName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CategoryID", unique = true, nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "CategoryName", nullable = false, length = 500)
    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

}
