package com.vtth.foodapi.entity;
// Generated May 16, 2016 2:59:42 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TblFood generated by hbm2java
 */
@Entity
@Table(name = "tbl_food", catalog = "fooddb")
public class TblFood implements java.io.Serializable {

    private Integer foodId;
    private TblCategory tblCategory;
    private String foodName;
    private String description;
    private String listMaterial;
    private String images;
    private TblFooddetail tblFooddetail;

    public TblFood() {
    }

    public TblFood(TblCategory tblCategory, String foodName) {
        this.tblCategory = tblCategory;
        this.foodName = foodName;
    }
    public TblFood(TblCategory tblCategory, String foodName, String description, String listMaterial, String images,
            TblFooddetail tblFooddetail) {
        this.tblCategory = tblCategory;
        this.foodName = foodName;
        this.description = description;
        this.listMaterial = listMaterial;
        this.images = images;
        this.tblFooddetail = tblFooddetail;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "FoodID", unique = true, nullable = false)
    public Integer getFoodId() {
        return this.foodId;
    }

    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CategoryID", nullable = false)
    public TblCategory getTblCategory() {
        return this.tblCategory;
    }

    public void setTblCategory(TblCategory tblCategory) {
        this.tblCategory = tblCategory;
    }

    @Column(name = "FoodName", nullable = false, length = 500)
    public String getFoodName() {
        return this.foodName;
    }

    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }

    @Column(name = "Description", length = 5000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "ListMaterial", length = 4000)
    public String getListMaterial() {
        return this.listMaterial;
    }

    public void setListMaterial(String listMaterial) {
        this.listMaterial = listMaterial;
    }

    @Column(name = "Images")
    public String getImages() {
        return this.images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "tblFood")
    public TblFooddetail getTblFooddetail() {
        return this.tblFooddetail;
    }

    public void setTblFooddetail(TblFooddetail tblFooddetail) {
        this.tblFooddetail = tblFooddetail;
    }

}
