package com.vtth.foodapi.entity;
// Generated Jun 2, 2016 2:47:32 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TblFood generated by hbm2java
 */
@Entity
@Table(name = "tbl_food", catalog = "fooddb")
public class TblFood implements java.io.Serializable {

    private Integer foodId;
    private String foodName;
    private String description;
    private String listMaterial;
    private String images;
    private Integer visitNum;
    private String tutorial;

    public TblFood() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "FoodID", unique = true, nullable = false)
    public Integer getFoodId() {
        return this.foodId;
    }

    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    @Column(name = "FoodName", nullable = false, length = 500)
    public String getFoodName() {
        return this.foodName;
    }

    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }

    @Column(name = "Description", length = 5000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "ListMaterial", length = 4000)
    public String getListMaterial() {
        return this.listMaterial;
    }

    public void setListMaterial(String listMaterial) {
        this.listMaterial = listMaterial;
    }

    @Column(name = "Images")
    public String getImages() {
        return this.images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    @Column(name = "VisitNum")
    public Integer getVisitNum() {
        return this.visitNum;
    }

    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    @Column(name = "Tutorial")
    public String getTutorial() {
        return this.tutorial;
    }

    public void setTutorial(String tutorial) {
        this.tutorial = tutorial;
    }

}
