package com.vtth.foodapi.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblFooddetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_fooddetail")
public class TblFooddetail implements java.io.Serializable {

    private static final long serialVersionUID = -7988799579036225137L;

    private int foodId;
    private String materialDetail;
    private String tutorial;
    private String source;

    @Id
    @Column(name = "FoodID", unique = true, nullable = false)
    public int getFoodId() {
        return this.foodId;
    }

    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }

    @Column(name = "MaterialDetail", length = 6000)
    public String getMaterialDetail() {
        return this.materialDetail;
    }

    public void setMaterialDetail(String materialDetail) {
        this.materialDetail = materialDetail;
    }

    @Column(name = "Tutorial", length = 15000)
    public String getTutorial() {
        return this.tutorial;
    }

    public void setTutorial(String tutorial) {
        this.tutorial = tutorial;
    }

    @Column(name = "Source")
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
