-- MySQL Script generated by MySQL Workbench
-- 05/25/16 16:49:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fooddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fooddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fooddb` DEFAULT CHARACTER SET utf8 ;
USE `fooddb` ;

-- -----------------------------------------------------
-- Table `fooddb`.`tbl_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooddb`.`tbl_category` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fooddb`.`tbl_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooddb`.`tbl_food` (
  `FoodID` INT(11) NOT NULL AUTO_INCREMENT,
  `FoodName` VARCHAR(500) NOT NULL,
  `Description` VARCHAR(5000) NULL DEFAULT NULL,
  `ListMaterial` VARCHAR(4000) NULL DEFAULT NULL,
  `Images` VARCHAR(255) NULL DEFAULT NULL,
  `VisitNum` INT(11) NULL DEFAULT NULL,
  `CategoryID` INT(11) NOT NULL,
  `LinkImage` VARCHAR(255) NULL DEFAULT NULL,
  `Tutorial` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`FoodID`),
  INDEX `CatetoryID_idx` (`CategoryID` ASC),
  CONSTRAINT `CatetoryID`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `fooddb`.`tbl_category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKlxa7sa726ubhc9wngvtd7f2yh`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `fooddb`.`tbl_category` (`CategoryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1045
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fooddb`.`tbl_fooddetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooddb`.`tbl_fooddetail` (
  `FoodID` INT(11) NOT NULL,
  `MaterialDetail` VARCHAR(6000) NULL DEFAULT NULL,
  `Tutorial` VARCHAR(15000) NULL DEFAULT NULL,
  `Source` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`FoodID`),
  CONSTRAINT `FoodID`
    FOREIGN KEY (`FoodID`)
    REFERENCES `fooddb`.`tbl_food` (`FoodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fooddb`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooddb`.`tbl_user` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fooddb`.`tbl_userdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fooddb`.`tbl_userdetail` (
  `UserID` INT(11) NOT NULL,
  `FullName` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `UserName`
    FOREIGN KEY (`UserID`)
    REFERENCES `fooddb`.`tbl_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `fooddb` ;

-- -----------------------------------------------------
-- procedure GetFood_ID
-- -----------------------------------------------------

DELIMITER $$
USE `fooddb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetFood_ID`(in Idsearch int)
BEGIN
	select FoodName, Images , MaterialInfo, Description from fooddb.tbl_food where  FoodID = Idsearch; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SearchFood_FoodName
-- -----------------------------------------------------

DELIMITER $$
USE `fooddb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SearchFood_FoodName`(in FoodNameSearch varchar(500))
BEGIN
	declare FinalSearch varchar(500) default '';
    
set FinalSearch = CONCAT('%',FoodNameSearch,'%');
    
select FoodName,Description from fooddb.tbl_food where  FoodName like FinalSearch; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SearchFood_Material
-- -----------------------------------------------------

DELIMITER $$
USE `fooddb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SearchFood_Material`(in Stringsearch varchar(2000),in member int,in ignorenumber int)
BEGIN
	declare search varchar(2000) default Stringsearch;
    
declare pointerFirst int(11) default 1;
    
declare pointerLast int (11) default 0;
    
declare maxlength int(11) default 0;
    
declare FinalSearch varchar(2000) default '%';
    
declare tmp varchar(255) default '%';
    
set maxlength = length(search);
    
processsearch: while ( pointerLast <> length(search)) do
    
set pointerLast = LOCATE(';',search);
    
set tmp = SUBSTRING(search FROM pointerFirst FOR pointerLast-1);
    
if tmp = '' then LEAVE processsearch; end if;
    
set FinalSearch = concat(FinalSearch,tmp,'%');
    
set search = SUBSTRING(search FROM pointerLast+1 FOR length(search));
    
end while processsearch;
    
select FoodName, Description from fooddb.tbl_food where  ListMaterial like FinalSearch order by VisitNum DESC limit member offset ignorenumber;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
